### ISSUE TITLE
Symbolic Math Scripting

### ISSUE THREAD

**Issue by axkr** [papdim/JShellLab#1]
Is it possible to use JShellLab as described in this article:
- https://dzone.com/articles/jshell-symbolic-math-scripting

Can HTML pages (Webview) or Java plotting frameworks be used?

**Comment by papdim** [comment]
Code such as:
sym("Integrate[x^(-1),x]")

sym("Integrate[x^a,x]");

sym("Integrate[x^10,x]")  // "1/11*x^11"
sym("Simplify[1/2*(2*x+2) ]")
sym("Simplify[1/2*(2*x+2)*(1/2)^(1/2)]")
sym("Simplify[Integrate[(8*x+1)/(x^2+x+1)^2,x]]")

can be executed with GroovyShell (F6), but there is a problem with JShell,
I have integrated an old version of JAS (file JASYMCA.jar), and these routines seem 
not to be called well from JShell.

Java plotting frameworks can be used, but of course with the proper classpath/imports setup.

**Comment by axkr** [comment]
Is where a download for JShellLab available?

Which of your labs projects is best suited to implement a console app interface like in our BETA android app?
- https://www.youtube.com/watch?v=fqjuFEA848s&feature=youtu.be
- https://github.com/axkr/symja_android_library/wiki/BETA-tests

The idea is to develop Symja scripts with an Windows/Linux **LAB** and use the same script in the Android app.
