### ISSUE TITLE
JShellLab and Windows/Eclipse environment

### ISSUE THREAD

**Issue by axkr** [papdim/JShellLab#2]
I got the JShellLab working under Windows in an Eclipse IDE and some basic jshell commands seems to be executed.

I commited my changes here because Eclipse shows some compiler errors:
- https://github.com/axkr/JShellLab/commits/master

How can I now integrate the jshell mechanism described here?
- https://github.com/axkr/symja_android_library/wiki/JShell-usage

Is there a mechanism to load the start-symja.jsh file mentioned in the wiki automatically for jshell instance?
How should I install the necessary jars (and deleting the old jasymca.jar)?

**Comment by papdim** [comment]
I removed an old version of the Java Algebra System from the standard libraries,
and now by using the symja_android_library  jar files within the extraJarsForJShellClasspath folder,
JAS  seems to work at least such code is executed:


import org.matheclipse.core.eval.ExprEvaluator;
import org.matheclipse.core.expression.F;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;
import org.matheclipse.parser.client.SyntaxError;
import org.matheclipse.parser.client.math.MathException;

ExprEvaluator util = new ExprEvaluator(false, 100);

String javaForm = util.toJavaForm("D(sin(x)*cos(x),x)");
			// prints: D(Times(Sin(x),Cos(x)),x)
			System.out.println("Out[1]: " + javaForm.toString());

ISymbol x = F.Dummy("x");
			IAST function = F.D(F.Times(F.Sin(x), F.Cos(x)), x);
			IExpr result = util.eval(function);
			// print: Cos(x)^2-Sin(x)^2
			System.out.println("Out[2]: " + result.toString());
